### PR TITLE
Fix Archlinux installaction instructions

### PR DESCRIPTION
**Pull request by milouse**
Fixes: https://github.com/liquidprompt/liquidprompt/issues/822

### CODE REVIEW

**Review by Rycieos — CHANGES_REQUESTED** [review]
Looks good, though the official name of the project is "Liquid Prompt". If you wouldn't mind amending the commit.

**Comment by milouse** [comment]
Done

Very sorry about that… I even checked before how to write it, but somehow failed to remember after reading it 🤦

**Comment by milouse** [comment]
(second force push to try to fix the doc lint error)

**Review by Rycieos — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
